# Generated by Django 6.0.1 on 2026-03-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuraNotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ai_grammar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='ai_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
