# Generated by Django 6.0.1 on 2026-03-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeuraNotes', '0002_note_ai_grammar_note_ai_summary_note_ai_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
